### ISSUE TITLE
Recent upstream changes to python-empy

### ISSUE THREAD

**Issue by kvmanohar22** [ros-noetic-arch/ros-noetic-catkin#6]
Hey all,

I recently updated my arch packages and this update has left ros in a broken state. And this is due to the upstream dependency `python-empy` package.

Recently [the package](https://gitlab.archlinux.org/archlinux/packaging/packages/python-empy/-/commit/79cdc768af855fae2ac99399b4270f6904bacbd7#9b9baac1eb9b72790eef5540a1685306fc43fd6c) `python-empy` was updated from 3.3.4 to 4.0.1. And 4.0.1 introduced quite a few breaking changes. And `ros-noetic-catkin` depends on this `python-empy` package.

Error while updating the `ros-noetic-*` packages after `pacman -Syu`:
```
Traceback (most recent call last):
  File "/opt/ros/noetic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 49, in <module>
  File "/opt/ros/noetic/share/gencpp/cmake/../../../lib/gencpp/gen_cpp.py", line 49, in <module>
    genmsg.template_tools.generate_from_command_line_options(
  File "/opt/ros/noetic/lib/python3.11/site-packages/genmsg/template_tools.py", line 213, in generate_from_command_line_options
    genmsg.template_tools.generate_from_command_line_options(
  File "/opt/ros/noetic/lib/python3.11/site-packages/genmsg/template_tools.py", line 213, in generate_from_command_line_options
    generate_from_file(argv[1], options.package, options.outdir, options.emdir, options.includepath, msg_template_dict, srv_template_dict)
    generate_from_file(argv[1], options.package, options.outdir, options.emdir, options.includepath, msg_template_dict, srv_template_dict)
  File "/opt/ros/noetic/lib/python3.11/site-packages/genmsg/template_tools.py", line 156, in generate_from_file
  File "/opt/ros/noetic/lib/python3.11/site-packages/genmsg/template_tools.py", line 154, in generate_from_file
    _generate_srv_from_file(input_file, output_dir, template_dir, search_path, package_name, srv_template_dict, msg_template_dict)
    _generate_msg_from_file(input_file, output_dir, template_dir, search_path, package_name, msg_template_dict)
  File "/opt/ros/noetic/lib/python3.11/site-packages/genmsg/template_tools.py", line 109, in _generate_srv_from_file
  File "/opt/ros/noetic/lib/python3.11/site-packages/genmsg/template_tools.py", line 93, in _generate_msg_from_file
    _generate_from_spec(input_file,
  File "/opt/ros/noetic/lib/python3.11/site-packages/genmsg/template_tools.py", line 77, in _generate_from_spec
    _generate_from_spec(input_file,
  File "/opt/ros/noetic/lib/python3.11/site-packages/genmsg/template_tools.py", line 77, in _generate_from_spec
    interpreter = em.Interpreter(output=ofile, globals=g, options={em.RAW_OPT:True,em.BUFFERED_OPT:True})
    interpreter = em.Interpreter(output=ofile, globals=g, options={em.RAW_OPT:True,em.BUFFERED_OPT:True})
                                                                   ^^^^^^^^^^
                                                                   ^^^^^^^^^^
AttributeError: module 'em' has no attribute 'RAW_OPT'
AttributeError: module 'em' has no attribute 'RAW_OPT'
```

It seems to me this can be resolved by explicitly specifying the last version which was working (3.3.4) in the `PKGBUILD` file. But this would pull in two packages i.e., 4.0.1 and 3.3.4.

Are we good to specify the package version 3.3.4 in the `PKGBUILD` file?

**Comment by cybaol** [comment]
@acxz 
[python-empy3](https://aur.archlinux.org/packages/python-empy3) exists on AUR. Please replace `python-empy` by `python-empy3`. Thanks!
